### ISSUE TITLE
Notify user when trying to install a package with known vulnerability

### ISSUE THREAD

**Issue by renyuneyun** [steffenfritz/pacaudit#4]
Hi, I just found this package and it seems to be quite useful.

I'm wondering (like mentioned in #1 ) if you'd like to add the ability to notify the user when the user tries to install a package which has known vulnerabilities.

I think this can be done by adding a pacman pre-hook. Maybe allowing user to select (Y/N) would be the best approach, but I'm not sure alpm pre-hooks can do this or not. (p.s. is it possible to add a switch / parameter to pacman?)
If not, it may be better if it can directly block the installation if the vulnerability is critical (and this behavior had better be configurable).

**Comment by steffenfritz** [comment]
Hi. Thanks for your comment. This would be definitely a great improvement. I will check ways to go for this.

**Comment by steffenfritz** [comment]
For reference: same request in the AUR: https://aur.archlinux.org/packages/pacaudit/

**Comment by steffenfritz** [comment]
Accepted, done and closed with v1.1.1

**Comment by renyuneyun** [comment]
That's great :)
