### ISSUE TITLE
Cannot install from AUR

### ISSUE THREAD

**Issue by r-darwish** [steffenfritz/pacaudit#5]
This is probably isn't related to pacaudit itself, but to https://fritz.wtf . The PKGBUILD tries to download https://fritz.wtf/v0.4.0.tar.gz.asc but fails because curl cannot contact the site:

```
*   Trying 159.69.212.31...
* TCP_NODELAY set
* Connected to fritz.wtf (159.69.212.31) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

My system is up to date and Firefox is able to contact the site. Is it possible that the site is misconfigured, as suggested [here](https://bbs.archlinux.org/viewtopic.php?id=235594)?

**Comment by steffenfritz** [comment]
Hi @r-darwish, thanks for the report. I'll check it out right away and then get back to you.

**Comment by steffenfritz** [comment]
Hi @r-darwish: Fixed, you can install now. There is also a warning with $srcdir. I will fix this the next few days. However, this should not affect the installation.
