### ISSUE TITLE
Make pacaudit exit non-zero when output != OK

### ISSUE THREAD

**Issue by Strykar** [steffenfritz/pacaudit#8]
To create a pre-transaction hook for `pacaudit` that uses the `AbortOnFail` feature, `pacaudit` needs to exit with a _non-zero_ code when the output of `pacaudit -n` is anything other than `OK`. This would fix https://github.com/steffenfritz/pacaudit/issues/4
Currently it exits with `0` even when the result is `Critical`:
```
$ pacaudit -n
Critical
$ echo $?
0
```
From https://www.archlinux.org/pacman/alpm-hooks.5.html:
```
AbortOnFail
Causes the transaction to be aborted if the hook exits non-zero.
Only applies to PreTransaction hooks.
```

_However_, this is part one of the issue to create a pre-transaction hook for pacaudit.
I'm open to suggestions on tackling this.
Currently, even if the non-zero codes were added for any `pacaudit -n` output other than `OK`, creating a pre-transaction hook with `AbortOnFail` would prevent a user from installing an insecure package even if they wished to force it. It would just abort and `pacman` would exit.

Perhaps we can go the route _Informant_, a pacman hook that prevents you from installing any packages until you read the latest Arch News update (if any fresh news is present from the last time Informant checked).
See https://github.com/bradford-smith94/informant

@steffenfritz To do this would require minor changes in pacaudit. Perhaps add a switch, to ensure the user has seen the list of insecure packages they wish to install and then run `pacman -Syu` again, which would succeed. This is the method Informant uses as pacman hooks are not designed to be interactive.

**Comment by steffenfritz** [comment]
I added a hook and a warning message is printed when a user installes a package listed as vulnerable. Not exactly the request. However, closed with v1.1.1
